<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="Themes\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CraftConsole.Core\CraftConsole.Core.csproj" />
    <ProjectReference Include="..\CraftConsole.Infrastructure\CraftConsole.Infrastructure.csproj" />
    <ProjectReference Include="..\CraftConsole.Modules.Console\CraftConsole.Modules.Console.csproj" />
    <ProjectReference Include="..\CraftConsole.Modules.Players\CraftConsole.Modules.Players.csproj" />
    <ProjectReference Include="..\CraftConsole.Modules.Plugins\CraftConsole.Modules.Plugins.csproj" />
    <ProjectReference Include="..\CraftConsole.Modules.Backup\CraftConsole.Modules.Backup.csproj" />
    <ProjectReference Include="..\CraftConsole.Modules.Scheduler\CraftConsole.Modules.Scheduler.csproj" />
    <ProjectReference Include="..\CraftConsole.Modules.Settings\CraftConsole.Modules.Settings.csproj" />
    <ProjectReference Include="..\CraftConsole.Modules.Dashboard\CraftConsole.Modules.Dashboard.csproj" />
    <ProjectReference Include="..\CraftConsole.Modules.Server\CraftConsole.Modules.Server.csproj" />
    <ProjectReference Include="..\CraftConsole.Modules.Issues\CraftConsole.Modules.Issues.csproj" />
    <ProjectReference Include="..\CraftConsole.Modules.Editor\CraftConsole.Modules.Editor.csproj" />
  </ItemGroup>
</Project>
